@host = http://localhost:5127/api

GET {{host}}/v1/get-user/8058233a-50ce-4463-a491-7aafe350d87e
Content-Type: application/json

###
GET {{host}}/v1/get-users
Content-Type: application/json

###
GET {{host}}/v1/get-group/1c975d1b-e62e-4a78-b4c0-286aa524ab6a
Content-Type: application/json