@host = http://localhost:5127/api

GET {{host}}/v1/get-user/ba4260c4-84dc-46e3-aa8e-0a0a6fc7a0ab
Content-Type: application/json

###
GET {{host}}/v1/get-users
Content-Type: application/json

###
GET {{host}}/v1/get-group/1c975d1b-e62e-4a78-b4c0-286aa524ab6a
Content-Type: application/json
###
GET {{host}}/v1/get-groups
Content-Type: application/json