@host = http://localhost:5127/api

POST  {{host}}/v1/create-user
Content-Type: application/json

{
    "name": "hugo",
    "password": "hhh",
    "phone": "112223222",
    "gifts": [
        {
            "description": "chinelo",
            "link": "/chinelo"
        }
    ]
}
###
POST  {{host}}/v1/create-group
Content-Type: application/json

{
    "drawDate": "2024-07-15T23:11",
    "giftsDate": "2024-07-17T23:11",
    "local": "casa da maria",
    "adminId": "ba4260c4-84dc-46e3-aa8e-0a0a6fc7a0ab"
}
###
POST  {{host}}/v1/group/add-players
Content-Type: application/json

{
    "groupId":"73674365-5f6e-4f93-804c-e877e60e215d",
    "players": [
        {
            "name": "player 1",
            "phone": "player 1",
            "gifts": [
                {
                    "description": "chinelo",
                    "link": "/chinelo"
                }
            ]
        },
        {
            "name": "player 2",
            "phone": "player 2",
            "gifts": [
                {
                    "description": "chinelo",
                    "link": "/chinelo"
                }
            ]
        }
    ]
}
###
POST  {{host}}/v1/group/draw-friends
Content-Type: application/json

{
    "groupId": "73674365-5f6e-4f93-804c-e877e60e215d"
}