@host = http://localhost:5127/api

POST  {{host}}/v1/create-user
Content-Type: application/json

{
    "name": "hugo",
    "password": "hhh",
    "phone": "11222333",
    "gifts": [
        {
            "description": "chinelo",
            "link": "/chinelo"
        }
    ]
}
###
POST  {{host}}/v1/create-group
Content-Type: application/json

{
    "drawDate": "2024-07-15T23:11",
    "giftsDate": "2024-07-17T23:11",
    "local": "casa da maria",
    "adminId": "f4df3774-06a2-4b90-9ab5-3ba8d11c62d5"
}
###
POST  {{host}}/v1/group/add-players
Content-Type: application/json

{
    "groupId":"73674365-5f6e-4f93-804c-e877e60e215d",
    "players": [
        {
            "name": "player 1",
            "phone": "player 1",
            "gifts": [
                {
                    "description": "chinelo",
                    "link": "/chinelo"
                }
            ]
        },
        {
            "name": "player 2",
            "phone": "player 2",
            "gifts": [
                {
                    "description": "chinelo",
                    "link": "/chinelo"
                }
            ]
        }
    ]
}
###
POST  {{host}}/v1/group/draw-friends
Content-Type: application/json

{
    "groupId": "73674365-5f6e-4f93-804c-e877e60e215d"
}